package pojos;
// Generated Jun 7, 2019 7:31:56 PM by Hibernate Tools 4.3.1

import javax.persistence.Id;




/**
 * Partlist generated by hbm2java
 */
public class Partlist  implements java.io.Serializable {    
     private PartlistId id;
     private Integer seq;
     private String partNo;
     private String partName;
     private Integer idpicking;
     private Integer qty;
     
     
    public Partlist() {
    }

	
    public Partlist(PartlistId id) {
        this.id = id;
    }
    public Partlist(PartlistId id,Integer seq0, String partNo, String partName, Integer idpicking, Integer qty) {
       this.id = id;
       this.id.setSeq(seq0);
       this.partNo = partNo;
       this.partName = partName;
       this.idpicking = idpicking;
       this.qty = qty;
    }
   
    public PartlistId getId() {
        return this.id;
    }
    
    public void setId(PartlistId id) {
        this.id = id;
    }
    
    public Integer getSeq() {
        return this.id.getSeq();
    }
    
    public void setSeq(Integer seq0) {
        this.id.setSeq(seq0);
    }
    
    public String getPartNo() {
        return this.partNo;
    }
    
    public void setPartNo(String partNo) {
        this.partNo = partNo;
    }
    public String getPartName() {
        return this.partName;
    }
    
    public void setPartName(String partName) {
        this.partName = partName;
    }
    public Integer getIdpicking() {
        return this.idpicking;
    }
    
    public void setIdpicking(Integer idpicking) {
        this.idpicking = idpicking;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


