package pojos;
// Generated Jun 7, 2019 7:31:56 PM by Hibernate Tools 4.3.1



/**
 * PartlistId generated by hbm2java
 */
public class PartlistId  implements java.io.Serializable {


     private String partKanban;
     private int seq;

    public PartlistId() {
    }

    public PartlistId(String partKanban, int seq) {
       this.partKanban = partKanban;
       this.seq = seq;
    }
   
    public String getPartKanban() {
        return this.partKanban;
    }
    
    public void setPartKanban(String partKanban) {
        this.partKanban = partKanban;
    }
    public int getSeq() {
        return this.seq;
    }
    
    public void setSeq(int seq) {
        this.seq = seq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PartlistId) ) return false;
		 PartlistId castOther = ( PartlistId ) other; 
         
		 return ( (this.getPartKanban()==castOther.getPartKanban()) || ( this.getPartKanban()!=null && castOther.getPartKanban()!=null && this.getPartKanban().equals(castOther.getPartKanban()) ) )
 && (this.getSeq()==castOther.getSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPartKanban() == null ? 0 : this.getPartKanban().hashCode() );
         result = 37 * result + this.getSeq();
         return result;
   }   


}


