package pojos;
// Generated Jun 7, 2019 7:31:56 PM by Hibernate Tools 4.3.1



/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private String partNo;
     private String partName;
     private Integer qty;

    public Stock() {
    }

	
    public Stock(String partNo) {
        this.partNo = partNo;
    }
    public Stock(String partNo, String partName, Integer qty) {
       this.partNo = partNo;
       this.partName = partName;
       this.qty = qty;
    }
   
    public String getPartNo() {
        return this.partNo;
    }
    
    public void setPartNo(String partNo) {
        this.partNo = partNo;
    }
    public String getPartName() {
        return this.partName;
    }
    
    public void setPartName(String partName) {
        this.partName = partName;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


